# Generated by Django 5.0.4 on 2024-04-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concessionaria', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('mes_referencia', models.CharField(max_length=2)),
                ('ano_referencia', models.CharField(max_length=4)),
                ('ponto_monitorado', models.CharField(max_length=50)),
                ('parametro', models.CharField(max_length=50)),
                ('valor_parametro', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
